# Generated by Django 5.0.2 on 2024-02-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_author_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "get_latest_by": "created_on",
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
    ]
