# Generated by Django 5.0.2 on 2024-02-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_author_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title", "author"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
    ]
