# Generated by Django 5.0.2 on 2024-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date of birth"),
        ),
    ]
