# Generated by Django 5.0.3 on 2024-03-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("published_on", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField()),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
