# Generated by Django 5.0.3 on 2024-03-13 11:02

import sanitizer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=sanitizer.models.SanitizedTextField(),
        ),
    ]
